[env]
TERM = "xterm-256color"

[font.normal]
family = "Meslo LGS NF"
style = "Regular"

[font.italic]
family = "Meslo LGS NF"
style = "Italic"

[font.bold]
family = "Meslo LGS NF"
style = "Bold"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[window]
padding.x = 10
padding.y = 10

[[keyboard.bindings]]
key = "F"
mods = "Control | Shift"
action = "ReceiveChar"

