[font]
normal.family = "Meslo LGS NF"

[colors.primary]
background = '0x181818'
foreground = '0xD4D4D4'

[colors.normal]
black =   '0x101010'
red =     '0xF44747'
green =   '0x608B4E'
yellow =  '0xD7BA7D'
blue =    '0x569CD6'
magenta = '0xC586C0'
cyan =    '0x9CDCFE'
white =   '0xD4D4D4'

[window]
padding.x = 10
padding.y = 10

[[keyboard.bindings]]
key = "F"
mods = "Control | Shift"
action = "ReceiveChar"

