#!/usr/bin/env bash

set -e

echo "Setup for nvm"

# Don't do anything if a .oh-my-zsh config directory exists
if [ -d $HOME/.nvm/ ]; then
  echo ".nvm directory found, skipping"
else
  export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
  ) && \. "$NVM_DIR/nvm.sh"
fi

echo "Setup for tpm"

if [ -d $HOME/.tmux/plugins/tpm ]; then
  echo "tpm directory found, skipping"
else
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
