#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Creating symlinks for .oh-my-zsh/custom/plugins ($SCRIPT_DIR)"

ln -sf "$SCRIPT_DIR"/* $HOME/.oh-my-zsh/custom/plugins/

rm $HOME/.oh-my-zsh/custom/plugins/link
