#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Creating symlinks for .local/bin ($SCRIPT_DIR)"

shopt -s dotglob
ln -sf "$SCRIPT_DIR"/* $HOME/.local/bin/

rm $HOME/.local/bin/dotfile_link
