#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Creating symlinks for ~ ($HOME from $SCRIPT_DIR)"

shopt -s dotglob
ln -sf "$SCRIPT_DIR"/* $HOME/

rm $HOME/dotfile_link
