#!/usr/bin/env bash

if [[ $# -gt 1 ]]; then
  exit 1
fi

__echo_lines() {
  while read p; do
    eval echo "$p"
  done < "$1" | sed "/^$/d"
}

__all_sessions() {
  # Find all directories inside parent dirs listed in find-dirs.conf
  find -L $(__echo_lines "$HOME/.config/tmux/find-dirs.conf") \
    -mindepth 1 -maxdepth 1 -type d \
    | grep --color=never ".*/[^.][^/]*$";

  # Output all session directories listed in session-dirs.conf
  __echo_lines "$HOME/.config/tmux/session-dirs.conf";
}

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(__all_sessions | fzf)
fi

if [[ -z $selected ]]; then
  exit 1
fi

echo $selected

