#!/usr/bin/env bash

if [[ $# -gt 1 ]]; then
  exit 1
fi

selected=$(select-project-dir $@)

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr .: _)

if [[ -z $TMUX ]]; then
  tmux new-session -s $selected_name -c $selected -A
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
