#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Creating symlinks for .config ($SCRIPT_DIR)"

ln -sf "$SCRIPT_DIR"/* $HOME/.config/

rm $HOME/.config/dotfile_link
