#!/bin/sh
case "$1" in
  dark)  KV="catppuccin-macchiato-blue" ;;
  light) KV="catppuccin-latte-blue" ;;
esac
mkdir -p "$HOME/.config/Kvantum"
printf '[General]\ntheme=%s\n' "$KV" > "$HOME/.config/Kvantum/kvantum.kvconfig"
