#!/bin/sh
# darkman/35-rofi — switch rofi theme between light (latte) and dark (macchiato)
case "$1" in
  dark)  src="catppuccin-macchiato" ;;
  light) src="catppuccin-latte" ;;
esac
cp "$HOME/.dotfiles/config/rofi/$src.rasi" "$HOME/.config/rofi/theme.rasi"
