#!/usr/bin/env bash

if [[ -n $1 ]]; then
  exit 0 
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Creating symlinks for darkman ($HOME/.local/share/darkman/ from $SCRIPT_DIR)"

shopt -s dotglob
ln -sf "$SCRIPT_DIR" $HOME/.local/share/darkman
